# Generated by Django 4.2.17 on 2026-01-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Sekolah')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('latitude', models.FloatField(help_text='Koordinat Lintang (Contoh: -6.502)')),
                ('longitude', models.FloatField(help_text='Koordinat Bujur (Contoh: 106.704)')),
                ('description', models.TextField(verbose_name='Profil Singkat Sekolah')),
                ('vision', models.TextField(blank=True, verbose_name='Visi')),
                ('mission', models.TextField(blank=True, verbose_name='Misi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website Sekolah')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='school_photos/', verbose_name='Foto Gedung')),
                ('headmaster_name', models.CharField(blank=True, max_length=100, verbose_name='Nama Kepala Sekolah')),
                ('headmaster_photo', models.ImageField(blank=True, null=True, upload_to='school_photos/', verbose_name='Foto Kepala Sekolah')),
            ],
            options={
                'verbose_name': 'Data Sekolah',
                'verbose_name_plural': 'Data Sekolah',
            },
        ),
        migrations.CreateModel(
            name='PPDBRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nama Lengkap Siswa')),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('birth_place', models.CharField(max_length=100, verbose_name='Tempat Lahir')),
                ('birth_date', models.DateField(verbose_name='Tanggal Lahir')),
                ('parent_name', models.CharField(max_length=150, verbose_name='Nama Orang Tua/Wali')),
                ('phone_number', models.CharField(max_length=20, verbose_name='No. WhatsApp')),
                ('address', models.TextField(verbose_name='Alamat Rumah')),
                ('booking_date', models.DateField(verbose_name='Rencana Datang ke Sekolah')),
                ('status', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Diterima', 'Diterima'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendaftar PPDB',
                'verbose_name_plural': 'Data Pendaftar PPDB',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Berita')),
                ('slug', models.SlugField(help_text='Link unik (misal: kegiatan-maulid)', unique=True)),
                ('content', models.TextField(verbose_name='Isi Berita')),
                ('image', models.ImageField(upload_to='news_photos/', verbose_name='Foto Kegiatan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Penulis')),
            ],
            options={
                'verbose_name': 'Berita & Kegiatan',
                'verbose_name_plural': 'Berita & Kegiatan',
                'ordering': ['-created_at'],
            },
        ),
    ]
