# Generated by Django 4.2.17 on 2025-12-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Sekolah')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('latitude', models.FloatField(help_text='Koordinat Lintang (Contoh: -6.502)')),
                ('longitude', models.FloatField(help_text='Koordinat Bujur (Contoh: 106.704)')),
                ('description', models.TextField(verbose_name='Profil Singkat Sekolah')),
                ('vision', models.TextField(blank=True, verbose_name='Visi')),
                ('mission', models.TextField(blank=True, verbose_name='Misi')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='school_photos/', verbose_name='Foto Gedung')),
                ('headmaster_name', models.CharField(blank=True, max_length=100, verbose_name='Nama Kepala Sekolah')),
                ('headmaster_photo', models.ImageField(blank=True, null=True, upload_to='school_photos/', verbose_name='Foto Kepala Sekolah')),
            ],
            options={
                'verbose_name': 'Data Sekolah',
                'verbose_name_plural': 'Data Sekolah',
            },
        ),
    ]
