# Generated by Django 4.2.17 on 2025-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website Sekolah'),
        ),
    ]
